query CharactersPage {
    characters {
        info {
            count
            pages
            next
            prev
        }
        results {
            id
            name
            status
            species 
            gender
            image
        }
    }
}